import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/test/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'lcov'],
      reportsDirectory: './coverage',
      include: [
        'electron/storage-*.ts',
        'electron/storage.ts',
        'electron/zip-archive.ts',
        'src/App.tsx',
        'src/components/editor/NoteContent.tsx',
        'src/components/editor/NoteEditor.tsx',
        'src/components/editor/NoteMetaBar.tsx',
        'src/components/editor/TagBar.tsx',
        'src/components/notes/NoteCard.tsx',
        'src/components/notes/NoteList.tsx',
        'src/components/search/QuickOpenModal.tsx',
        'src/components/ui/UpdateBanner.tsx',
        'src/hooks/useAppState.ts',
        'src/lib/desktop-errors.ts',
        'src/lib/markdown.ts',
        'src/lib/quick-open.ts',
      ],
      exclude: [
        'coverage/**',
        'dist-electron/**',
        'dist/**',
        'electron/**/*.d.ts',
        'electron/main.ts',
        'electron/navigation.ts',
        'electron/preload.ts',
        'eslint.config.mjs',
        'playwright.config.ts',
        'postcss.config.js',
        'scripts/**',
        'src/data/mock.ts',
        'src/main.tsx',
        'src/test/**',
        'src/types/**',
        'tailwind.config.js',
        'tests/**',
        'vite.config.ts',
        'vitest*.config.ts',
      ],
      thresholds: {
        statements: 70,
        lines: 70,
        functions: 70,
        branches: 60,
      },
    },
  },
});
